baseURL = 'https://chaco.dev/fabevents/'
languageCode = 'en-us'
title = 'FAB Events Calendar'

[params]
  description = "Subscribe to FAB TCG event calendars - Local DFW events and Major Global events"
  author = "Chase"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
